services:
  app:
    build:
      context: .
      target: prod
    container_name: doro-shop-app-prod
    ports:
      - "3001:3001"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://doroshop01:doroshop@cluster0.p6vosmo.mongodb.net/doros?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped

  # mongo:
  #   image: mongo
  #   container_name: mongo-prod
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  #   restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-prod
    ports:
      - "5000:6379"
    restart: unless-stopped

# volumes:
#   mongo-data: